-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [cpoly]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace cpoly

/-- [cpoly::cmlpoly::pow2]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 55:4-58:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.pow2_loop.body
  (n : Std.Usize) (m : Std.Usize) (k : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Std.Usize)
  := do
  if k < n
  then let m1 ← m * 2#usize
       let k1 ← k + 1#usize
       ok (cont (m1, k1))
  else ok (done m)

/-- [cpoly::cmlpoly::pow2]: loop 0:
    Source: 'src/cmlpoly.rs', lines 55:4-58:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.pow2_loop
  (n : Std.Usize) (m : Std.Usize) (k : Std.Usize) : Result Std.Usize := do
  loop
    (fun (m1, k1) => cmlpoly.pow2_loop.body n m1 k1)
    (m, k)

/-- [cpoly::cmlpoly::pow2]:
    Source: 'src/cmlpoly.rs', lines 52:0-60:1
    Visibility: public -/
@[reducible]
def cmlpoly.pow2 (n : Std.Usize) : Result Std.Usize := do
  cmlpoly.pow2_loop n 1#usize 0#usize

/-- [cpoly::field::Ext4]
    Source: 'src/field.rs', lines 87:0-92:1
    Visibility: public -/
structure field.Ext4 where
  c0 : Std.U64
  c1 : Std.U64
  c2 : Std.U64
  c3 : Std.U64

/-- [cpoly::field::EZERO]
    Source: 'src/field.rs', lines 95:0-100:2
    Visibility: public -/
@[global_simps, irreducible]
def field.EZERO : field.Ext4 :=
  { c0 := 0#u64, c1 := 0#u64, c2 := 0#u64, c3 := 0#u64 }

/-- [cpoly::cmlpoly::zero]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 71:4-74:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.zero_loop.body
  (sz : Std.Usize) (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < sz
  then
    let r1 ← alloc.vec.Vec.push r field.EZERO
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::cmlpoly::zero]: loop 0:
    Source: 'src/cmlpoly.rs', lines 71:4-74:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.zero_loop
  (sz : Std.Usize) (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cmlpoly.zero_loop.body sz r1 i1)
    (r, i)

/-- [cpoly::cmlpoly::zero]:
    Source: 'src/cmlpoly.rs', lines 67:0-76:1
    Visibility: public -/
def cmlpoly.zero (n : Std.Usize) : Result (alloc.vec.Vec field.Ext4) := do
  let sz ← cmlpoly.pow2 n
  cmlpoly.zero_loop sz (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::cmlpoly::of_array]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 85:4-92:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.of_array_loop.body
  (coeffs : alloc.vec.Vec field.Ext4) (sz : Std.Usize) (m : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < sz
  then
    let r1 ←
      if i < m
      then
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) coeffs i
        alloc.vec.Vec.push r e
      else alloc.vec.Vec.push r field.EZERO
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::cmlpoly::of_array]: loop 0:
    Source: 'src/cmlpoly.rs', lines 85:4-92:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.of_array_loop
  (coeffs : alloc.vec.Vec field.Ext4) (sz : Std.Usize) (m : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cmlpoly.of_array_loop.body coeffs sz m r1 i1)
    (r, i)

/-- [cpoly::cmlpoly::of_array]:
    Source: 'src/cmlpoly.rs', lines 80:0-94:1
    Visibility: public -/
def cmlpoly.of_array
  (coeffs : alloc.vec.Vec field.Ext4) (n : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let sz ← cmlpoly.pow2 n
  let m := alloc.vec.Vec.len coeffs
  cmlpoly.of_array_loop coeffs sz m (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::field::P]
    Source: 'src/field.rs', lines 41:0-41:30
    Visibility: public -/
@[global_simps, irreducible] def field.P : Std.U64 := 4294967197#u64

/-- [cpoly::field::fadd]:
    Source: 'src/field.rs', lines 56:0-58:1
    Visibility: public -/
def field.fadd (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← a + b
  i % field.P

/-- [cpoly::field::eadd]:
    Source: 'src/field.rs', lines 137:0-144:1
    Visibility: public -/
def field.eadd (a : field.Ext4) (b : field.Ext4) : Result field.Ext4 := do
  let i ← field.fadd a.c0 b.c0
  let i1 ← field.fadd a.c1 b.c1
  let i2 ← field.fadd a.c2 b.c2
  let i3 ← field.fadd a.c3 b.c3
  ok { c0 := i, c1 := i1, c2 := i2, c3 := i3 }

/-- [cpoly::cmlpoly::add]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 105:4-109:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.add_loop.body
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < n
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i
    let e1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) q
        i
    let s ← field.eadd e e1
    let r1 ← alloc.vec.Vec.push r s
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::cmlpoly::add]: loop 0:
    Source: 'src/cmlpoly.rs', lines 105:4-109:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.add_loop
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cmlpoly.add_loop.body p q n r1 i1)
    (r, i)

/-- [cpoly::cmlpoly::add]:
    Source: 'src/cmlpoly.rs', lines 101:0-111:1
    Visibility: public -/
def cmlpoly.add
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let n := alloc.vec.Vec.len p
  cmlpoly.add_loop p q n (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::field::fmul]:
    Source: 'src/field.rs', lines 66:0-68:1
    Visibility: public -/
def field.fmul (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← a * b
  i % field.P

/-- [cpoly::field::W]
    Source: 'src/field.rs', lines 47:0-47:21
    Visibility: public -/
@[global_simps, irreducible] def field.W : Std.U64 := 2#u64

/-- [cpoly::field::emul]:
    Source: 'src/field.rs', lines 172:0-189:1
    Visibility: public -/
def field.emul (a : field.Ext4) (b : field.Ext4) : Result field.Ext4 := do
  let t0 ← field.fmul a.c0 b.c0
  let i ← field.fmul a.c0 b.c1
  let i1 ← field.fmul a.c1 b.c0
  let t1 ← field.fadd i i1
  let i2 ← field.fmul a.c0 b.c2
  let i3 ← field.fmul a.c1 b.c1
  let i4 ← field.fadd i2 i3
  let i5 ← field.fmul a.c2 b.c0
  let t2 ← field.fadd i4 i5
  let i6 ← field.fmul a.c0 b.c3
  let i7 ← field.fmul a.c1 b.c2
  let i8 ← field.fadd i6 i7
  let i9 ← field.fmul a.c2 b.c1
  let i10 ← field.fadd i8 i9
  let i11 ← field.fmul a.c3 b.c0
  let t3 ← field.fadd i10 i11
  let i12 ← field.fmul a.c1 b.c3
  let i13 ← field.fmul a.c2 b.c2
  let i14 ← field.fadd i12 i13
  let i15 ← field.fmul a.c3 b.c1
  let t4 ← field.fadd i14 i15
  let i16 ← field.fmul a.c2 b.c3
  let i17 ← field.fmul a.c3 b.c2
  let t5 ← field.fadd i16 i17
  let t6 ← field.fmul a.c3 b.c3
  let i18 ← field.fmul field.W t4
  let i19 ← field.fadd t0 i18
  let i20 ← field.fmul field.W t5
  let i21 ← field.fadd t1 i20
  let i22 ← field.fmul field.W t6
  let i23 ← field.fadd t2 i22
  ok { c0 := i19, c1 := i21, c2 := i23, c3 := t3 }

/-- [cpoly::field::EONE]
    Source: 'src/field.rs', lines 103:0-108:2
    Visibility: public -/
@[global_simps, irreducible]
def field.EONE : field.Ext4 :=
  { c0 := 1#u64, c1 := 0#u64, c2 := 0#u64, c3 := 0#u64 }

/-- [cpoly::cmlpoly::monomial_basis]: loop body 1:
    Source: 'src/cmlpoly.rs', lines 131:8-137:9
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.monomial_basis_loop0_loop0.body
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (acc : field.Ext4)
  (m : Std.Usize) (j : Std.Usize) :
  Result (ControlFlow (field.Ext4 × Std.Usize × Std.Usize) field.Ext4)
  := do
  if j < n
  then
    let i ← m % 2#usize
    let acc1 ←
      if i = 1#usize
      then
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) w j
        field.emul acc e
      else ok acc
    let m1 ← m / 2#usize
    let j1 ← j + 1#usize
    ok (cont (acc1, m1, j1))
  else ok (done acc)

/-- [cpoly::cmlpoly::monomial_basis]: loop 1:
    Source: 'src/cmlpoly.rs', lines 131:8-137:9
    Visibility: public -/
@[rust_loop]
def cmlpoly.monomial_basis_loop0_loop0
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (acc : field.Ext4)
  (m : Std.Usize) (j : Std.Usize) :
  Result field.Ext4
  := do
  loop
    (fun (acc1, m1, j1) => cmlpoly.monomial_basis_loop0_loop0.body w n acc1 m1
      j1)
    (acc, m, j)

/-- [cpoly::cmlpoly::monomial_basis]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 127:4-140:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.monomial_basis_loop0.body
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (sz : Std.Usize)
  (basis : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < sz
  then
    let acc ← cmlpoly.monomial_basis_loop0_loop0 w n field.EONE i 0#usize
    let basis1 ← alloc.vec.Vec.push basis acc
    let i1 ← i + 1#usize
    ok (cont (basis1, i1))
  else ok (done basis)

/-- [cpoly::cmlpoly::monomial_basis]: loop 0:
    Source: 'src/cmlpoly.rs', lines 127:4-140:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.monomial_basis_loop0
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (sz : Std.Usize)
  (basis : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (basis1, i1) => cmlpoly.monomial_basis_loop0.body w n sz basis1 i1)
    (basis, i)

/-- [cpoly::cmlpoly::monomial_basis]:
    Source: 'src/cmlpoly.rs', lines 122:0-142:1
    Visibility: public -/
def cmlpoly.monomial_basis
  (w : alloc.vec.Vec field.Ext4) : Result (alloc.vec.Vec field.Ext4) := do
  let n := alloc.vec.Vec.len w
  let sz ← cmlpoly.pow2 n
  cmlpoly.monomial_basis_loop0 w n sz (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::field::fsub]:
    Source: 'src/field.rs', lines 61:0-63:1
    Visibility: public -/
def field.fsub (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← a + field.P
  let i1 ← i - b
  i1 % field.P

/-- [cpoly::field::esub]:
    Source: 'src/field.rs', lines 147:0-154:1
    Visibility: public -/
def field.esub (a : field.Ext4) (b : field.Ext4) : Result field.Ext4 := do
  let i ← field.fsub a.c0 b.c0
  let i1 ← field.fsub a.c1 b.c1
  let i2 ← field.fsub a.c2 b.c2
  let i3 ← field.fsub a.c3 b.c3
  ok { c0 := i, c1 := i1, c2 := i2, c3 := i3 }

/-- [cpoly::cmlpoly::lagrange_basis]: loop body 1:
    Source: 'src/cmlpoly.rs', lines 156:8-165:9
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.lagrange_basis_loop0_loop0.body
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (acc : field.Ext4)
  (m : Std.Usize) (j : Std.Usize) :
  Result (ControlFlow (field.Ext4 × Std.Usize × Std.Usize) field.Ext4)
  := do
  if j < n
  then
    let i ← m % 2#usize
    let acc1 ←
      if i = 1#usize
      then
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) w j
        field.emul acc e
      else
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) w j
        let t ← field.esub field.EONE e
        field.emul acc t
    let m1 ← m / 2#usize
    let j1 ← j + 1#usize
    ok (cont (acc1, m1, j1))
  else ok (done acc)

/-- [cpoly::cmlpoly::lagrange_basis]: loop 1:
    Source: 'src/cmlpoly.rs', lines 156:8-165:9
    Visibility: public -/
@[rust_loop]
def cmlpoly.lagrange_basis_loop0_loop0
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (acc : field.Ext4)
  (m : Std.Usize) (j : Std.Usize) :
  Result field.Ext4
  := do
  loop
    (fun (acc1, m1, j1) => cmlpoly.lagrange_basis_loop0_loop0.body w n acc1 m1
      j1)
    (acc, m, j)

/-- [cpoly::cmlpoly::lagrange_basis]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 152:4-168:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.lagrange_basis_loop0.body
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (sz : Std.Usize)
  (basis : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < sz
  then
    let acc ← cmlpoly.lagrange_basis_loop0_loop0 w n field.EONE i 0#usize
    let basis1 ← alloc.vec.Vec.push basis acc
    let i1 ← i + 1#usize
    ok (cont (basis1, i1))
  else ok (done basis)

/-- [cpoly::cmlpoly::lagrange_basis]: loop 0:
    Source: 'src/cmlpoly.rs', lines 152:4-168:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.lagrange_basis_loop0
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize) (sz : Std.Usize)
  (basis : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (basis1, i1) => cmlpoly.lagrange_basis_loop0.body w n sz basis1 i1)
    (basis, i)

/-- [cpoly::cmlpoly::lagrange_basis]:
    Source: 'src/cmlpoly.rs', lines 147:0-170:1
    Visibility: public -/
def cmlpoly.lagrange_basis
  (w : alloc.vec.Vec field.Ext4) : Result (alloc.vec.Vec field.Ext4) := do
  let n := alloc.vec.Vec.len w
  let sz ← cmlpoly.pow2 n
  cmlpoly.lagrange_basis_loop0 w n sz (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::cmlpoly::dot]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 182:4-186:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.dot_loop.body
  (a : alloc.vec.Vec field.Ext4) (b : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (acc : field.Ext4) (i : Std.Usize) :
  Result (ControlFlow (field.Ext4 × Std.Usize) field.Ext4)
  := do
  if i < n
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) a
        i
    let e1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) b
        i
    let t ← field.emul e e1
    let acc1 ← field.eadd acc t
    let i1 ← i + 1#usize
    ok (cont (acc1, i1))
  else ok (done acc)

/-- [cpoly::cmlpoly::dot]: loop 0:
    Source: 'src/cmlpoly.rs', lines 182:4-186:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.dot_loop
  (a : alloc.vec.Vec field.Ext4) (b : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (acc : field.Ext4) (i : Std.Usize) :
  Result field.Ext4
  := do
  loop
    (fun (acc1, i1) => cmlpoly.dot_loop.body a b n acc1 i1)
    (acc, i)

/-- [cpoly::cmlpoly::dot]:
    Source: 'src/cmlpoly.rs', lines 179:0-188:1
    Visibility: public -/
@[reducible]
def cmlpoly.dot
  (a : alloc.vec.Vec field.Ext4) (b : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  :
  Result field.Ext4
  := do
  cmlpoly.dot_loop a b n field.EZERO 0#usize

/-- [cpoly::cmlpoly::eval]:
    Source: 'src/cmlpoly.rs', lines 192:0-196:1
    Visibility: public -/
def cmlpoly.eval
  (p : alloc.vec.Vec field.Ext4) (w : alloc.vec.Vec field.Ext4) :
  Result field.Ext4
  := do
  let basis ← cmlpoly.monomial_basis w
  let sz := alloc.vec.Vec.len basis
  cmlpoly.dot p basis sz

/-- [cpoly::cmlpoly::eval_lagrange]:
    Source: 'src/cmlpoly.rs', lines 201:0-205:1
    Visibility: public -/
def cmlpoly.eval_lagrange
  (p : alloc.vec.Vec field.Ext4) (w : alloc.vec.Vec field.Ext4) :
  Result field.Ext4
  := do
  let basis ← cmlpoly.lagrange_basis w
  let sz := alloc.vec.Vec.len basis
  cmlpoly.dot p basis sz

/-- [cpoly::cmlpoly::eq_tilde]:
    Source: 'src/cmlpoly.rs', lines 209:0-212:1
    Visibility: public -/
def cmlpoly.eq_tilde
  (w : alloc.vec.Vec field.Ext4) (x : alloc.vec.Vec field.Ext4) :
  Result field.Ext4
  := do
  let b ← cmlpoly.lagrange_basis w
  cmlpoly.eval_lagrange b x

/-- [cpoly::cmlpoly::eval_horner_layer]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 227:4-234:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.eval_horner_layer_loop.body
  (coeffs : alloc.vec.Vec field.Ext4) (x0 : field.Ext4) (half : Std.Usize)
  (out : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if j < half
  then
    let i ← 2#usize * j
    let lo ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4)
        coeffs i
    let i1 ← i + 1#usize
    let hi ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4)
        coeffs i1
    let t ← field.emul x0 hi
    let v ← field.eadd lo t
    let out1 ← alloc.vec.Vec.push out v
    let j1 ← j + 1#usize
    ok (cont (out1, j1))
  else ok (done out)

/-- [cpoly::cmlpoly::eval_horner_layer]: loop 0:
    Source: 'src/cmlpoly.rs', lines 227:4-234:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.eval_horner_layer_loop
  (coeffs : alloc.vec.Vec field.Ext4) (x0 : field.Ext4) (half : Std.Usize)
  (out : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (out1, j1) => cmlpoly.eval_horner_layer_loop.body coeffs x0 half out1
      j1)
    (out, j)

/-- [cpoly::cmlpoly::eval_horner_layer]:
    Source: 'src/cmlpoly.rs', lines 223:0-236:1
    Visibility: public -/
def cmlpoly.eval_horner_layer
  (coeffs : alloc.vec.Vec field.Ext4) (x0 : field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let i := alloc.vec.Vec.len coeffs
  let half ← i / 2#usize
  cmlpoly.eval_horner_layer_loop coeffs x0 half (alloc.vec.Vec.new field.Ext4)
    0#usize

/-- [cpoly::cmlpoly::eval_horner]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 248:4-251:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.eval_horner_loop0.body
  (p : alloc.vec.Vec field.Ext4) (sz : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < sz
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i
    let cur1 ← alloc.vec.Vec.push cur e
    let i1 ← i + 1#usize
    ok (cont (cur1, i1))
  else ok (done cur)

/-- [cpoly::cmlpoly::eval_horner]: loop 0:
    Source: 'src/cmlpoly.rs', lines 248:4-251:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.eval_horner_loop0
  (p : alloc.vec.Vec field.Ext4) (sz : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (cur1, i1) => cmlpoly.eval_horner_loop0.body p sz cur1 i1)
    (cur, i)

/-- [cpoly::cmlpoly::eval_horner]: loop body 1:
    Source: 'src/cmlpoly.rs', lines 253:4-256:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.eval_horner_loop1.body
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if j < n
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) w
        j
    let cur1 ← cmlpoly.eval_horner_layer cur e
    let j1 ← j + 1#usize
    ok (cont (cur1, j1))
  else ok (done cur)

/-- [cpoly::cmlpoly::eval_horner]: loop 1:
    Source: 'src/cmlpoly.rs', lines 253:4-256:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.eval_horner_loop1
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (cur1, j1) => cmlpoly.eval_horner_loop1.body w n cur1 j1)
    (cur, j)

/-- [cpoly::cmlpoly::eval_horner]:
    Source: 'src/cmlpoly.rs', lines 243:0-258:1
    Visibility: public -/
def cmlpoly.eval_horner
  (p : alloc.vec.Vec field.Ext4) (w : alloc.vec.Vec field.Ext4) :
  Result field.Ext4
  := do
  let n := alloc.vec.Vec.len w
  let sz ← cmlpoly.pow2 n
  let cur ←
    cmlpoly.eval_horner_loop0 p sz (alloc.vec.Vec.new field.Ext4) 0#usize
  let cur1 ← cmlpoly.eval_horner_loop1 w n cur 0#usize
  alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) cur1
    0#usize

/-- [cpoly::cmlpoly::eval_mle_layer]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 270:4-278:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.eval_mle_layer_loop.body
  (values : alloc.vec.Vec field.Ext4) (x0 : field.Ext4) (half : Std.Usize)
  (one_minus : field.Ext4) (out : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if j < half
  then
    let i ← 2#usize * j
    let lo ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4)
        values i
    let i1 ← i + 1#usize
    let hi ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4)
        values i1
    let a ← field.emul one_minus lo
    let b ← field.emul x0 hi
    let v ← field.eadd a b
    let out1 ← alloc.vec.Vec.push out v
    let j1 ← j + 1#usize
    ok (cont (out1, j1))
  else ok (done out)

/-- [cpoly::cmlpoly::eval_mle_layer]: loop 0:
    Source: 'src/cmlpoly.rs', lines 270:4-278:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.eval_mle_layer_loop
  (values : alloc.vec.Vec field.Ext4) (x0 : field.Ext4) (half : Std.Usize)
  (one_minus : field.Ext4) (out : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (out1, j1) => cmlpoly.eval_mle_layer_loop.body values x0 half
      one_minus out1 j1)
    (out, j)

/-- [cpoly::cmlpoly::eval_mle_layer]:
    Source: 'src/cmlpoly.rs', lines 265:0-280:1
    Visibility: public -/
def cmlpoly.eval_mle_layer
  (values : alloc.vec.Vec field.Ext4) (x0 : field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let i := alloc.vec.Vec.len values
  let half ← i / 2#usize
  let one_minus ← field.esub field.EONE x0
  cmlpoly.eval_mle_layer_loop values x0 half one_minus (alloc.vec.Vec.new
    field.Ext4) 0#usize

/-- [cpoly::cmlpoly::eval_mle]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 289:4-292:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.eval_mle_loop0.body
  (values : alloc.vec.Vec field.Ext4) (sz : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < sz
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4)
        values i
    let cur1 ← alloc.vec.Vec.push cur e
    let i1 ← i + 1#usize
    ok (cont (cur1, i1))
  else ok (done cur)

/-- [cpoly::cmlpoly::eval_mle]: loop 0:
    Source: 'src/cmlpoly.rs', lines 289:4-292:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.eval_mle_loop0
  (values : alloc.vec.Vec field.Ext4) (sz : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (cur1, i1) => cmlpoly.eval_mle_loop0.body values sz cur1 i1)
    (cur, i)

/-- [cpoly::cmlpoly::eval_mle]: loop body 1:
    Source: 'src/cmlpoly.rs', lines 294:4-297:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.eval_mle_loop1.body
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if j < n
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) w
        j
    let cur1 ← cmlpoly.eval_mle_layer cur e
    let j1 ← j + 1#usize
    ok (cont (cur1, j1))
  else ok (done cur)

/-- [cpoly::cmlpoly::eval_mle]: loop 1:
    Source: 'src/cmlpoly.rs', lines 294:4-297:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.eval_mle_loop1
  (w : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (cur1, j1) => cmlpoly.eval_mle_loop1.body w n cur1 j1)
    (cur, j)

/-- [cpoly::cmlpoly::eval_mle]:
    Source: 'src/cmlpoly.rs', lines 284:0-299:1
    Visibility: public -/
def cmlpoly.eval_mle
  (values : alloc.vec.Vec field.Ext4) (w : alloc.vec.Vec field.Ext4) :
  Result field.Ext4
  := do
  let n := alloc.vec.Vec.len w
  let sz ← cmlpoly.pow2 n
  let cur ←
    cmlpoly.eval_mle_loop0 values sz (alloc.vec.Vec.new field.Ext4) 0#usize
  let cur1 ← cmlpoly.eval_mle_loop1 w n cur 0#usize
  alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) cur1
    0#usize

/-- [cpoly::cmlpoly::mono_to_lagrange_level]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 317:4-325:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.mono_to_lagrange_level_loop.body
  (v : alloc.vec.Vec field.Ext4) (n : Std.Usize) (stride : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < n
  then
    let i1 ← i / stride
    let i2 ← i1 % 2#usize
    let r1 ←
      if i2 = 1#usize
      then
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) v i
        let i3 ← i - stride
        let e1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) v i3
        let s ← field.eadd e e1
        alloc.vec.Vec.push r s
      else
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) v i
        alloc.vec.Vec.push r e
    let i3 ← i + 1#usize
    ok (cont (r1, i3))
  else ok (done r)

/-- [cpoly::cmlpoly::mono_to_lagrange_level]: loop 0:
    Source: 'src/cmlpoly.rs', lines 317:4-325:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.mono_to_lagrange_level_loop
  (v : alloc.vec.Vec field.Ext4) (n : Std.Usize) (stride : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cmlpoly.mono_to_lagrange_level_loop.body v n stride r1 i1)
    (r, i)

/-- [cpoly::cmlpoly::mono_to_lagrange_level]:
    Source: 'src/cmlpoly.rs', lines 312:0-327:1
    Visibility: public -/
def cmlpoly.mono_to_lagrange_level
  (v : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let n := alloc.vec.Vec.len v
  let stride ← cmlpoly.pow2 j
  cmlpoly.mono_to_lagrange_level_loop v n stride (alloc.vec.Vec.new field.Ext4)
    0#usize

/-- [cpoly::cmlpoly::mono_to_lagrange]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 336:4-339:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.mono_to_lagrange_loop.body
  (n : Std.Usize) (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if j < n
  then
    let cur1 ← cmlpoly.mono_to_lagrange_level cur j
    let j1 ← j + 1#usize
    ok (cont (cur1, j1))
  else ok (done cur)

/-- [cpoly::cmlpoly::mono_to_lagrange]: loop 0:
    Source: 'src/cmlpoly.rs', lines 336:4-339:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.mono_to_lagrange_loop
  (n : Std.Usize) (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (cur1, j1) => cmlpoly.mono_to_lagrange_loop.body n cur1 j1)
    (cur, j)

/-- [cpoly::cmlpoly::mono_to_lagrange]:
    Source: 'src/cmlpoly.rs', lines 333:0-341:1
    Visibility: public -/
@[reducible]
def cmlpoly.mono_to_lagrange
  (v : alloc.vec.Vec field.Ext4) (n : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  cmlpoly.mono_to_lagrange_loop n v 0#usize

/-- [cpoly::cmlpoly::lagrange_to_mono_level]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 355:4-363:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.lagrange_to_mono_level_loop.body
  (v : alloc.vec.Vec field.Ext4) (n : Std.Usize) (stride : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < n
  then
    let i1 ← i / stride
    let i2 ← i1 % 2#usize
    let r1 ←
      if i2 = 1#usize
      then
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) v i
        let i3 ← i - stride
        let e1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) v i3
        let s ← field.esub e e1
        alloc.vec.Vec.push r s
      else
        do
        let e ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            field.Ext4) v i
        alloc.vec.Vec.push r e
    let i3 ← i + 1#usize
    ok (cont (r1, i3))
  else ok (done r)

/-- [cpoly::cmlpoly::lagrange_to_mono_level]: loop 0:
    Source: 'src/cmlpoly.rs', lines 355:4-363:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.lagrange_to_mono_level_loop
  (v : alloc.vec.Vec field.Ext4) (n : Std.Usize) (stride : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cmlpoly.lagrange_to_mono_level_loop.body v n stride r1 i1)
    (r, i)

/-- [cpoly::cmlpoly::lagrange_to_mono_level]:
    Source: 'src/cmlpoly.rs', lines 350:0-365:1
    Visibility: public -/
def cmlpoly.lagrange_to_mono_level
  (v : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let n := alloc.vec.Vec.len v
  let stride ← cmlpoly.pow2 j
  cmlpoly.lagrange_to_mono_level_loop v n stride (alloc.vec.Vec.new field.Ext4)
    0#usize

/-- [cpoly::cmlpoly::lagrange_to_mono]: loop body 0:
    Source: 'src/cmlpoly.rs', lines 372:4-375:5
    Visibility: public -/
@[rust_loop_body]
def cmlpoly.lagrange_to_mono_loop.body
  (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if j > 0#usize
  then
    let j1 ← j - 1#usize
    let cur1 ← cmlpoly.lagrange_to_mono_level cur j1
    ok (cont (cur1, j1))
  else ok (done cur)

/-- [cpoly::cmlpoly::lagrange_to_mono]: loop 0:
    Source: 'src/cmlpoly.rs', lines 372:4-375:5
    Visibility: public -/
@[rust_loop]
def cmlpoly.lagrange_to_mono_loop
  (cur : alloc.vec.Vec field.Ext4) (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (cur1, j1) => cmlpoly.lagrange_to_mono_loop.body cur1 j1)
    (cur, j)

/-- [cpoly::cmlpoly::lagrange_to_mono]:
    Source: 'src/cmlpoly.rs', lines 369:0-377:1
    Visibility: public -/
@[reducible]
def cmlpoly.lagrange_to_mono
  (v : alloc.vec.Vec field.Ext4) (n : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  cmlpoly.lagrange_to_mono_loop v n

/-- [cpoly::cpoly::c]:
    Source: 'src/cpoly.rs', lines 32:0-36:1
    Visibility: public -/
def cpoly.c (r : field.Ext4) : Result (alloc.vec.Vec field.Ext4) := do
  alloc.vec.Vec.push (alloc.vec.Vec.new field.Ext4) r

/-- [cpoly::cpoly::x]:
    Source: 'src/cpoly.rs', lines 39:0-44:1
    Visibility: public -/
def cpoly.x : Result (alloc.vec.Vec field.Ext4) := do
  let p ← alloc.vec.Vec.push (alloc.vec.Vec.new field.Ext4) field.EZERO
  alloc.vec.Vec.push p field.EONE

/-- [cpoly::field::is_ezero]:
    Source: 'src/field.rs', lines 132:0-134:1
    Visibility: public -/
def field.is_ezero (a : field.Ext4) : Result Bool := do
  if a.c0 = 0#u64
  then
    if a.c1 = 0#u64
    then if a.c2 = 0#u64
         then ok (a.c3 = 0#u64)
         else ok false
    else ok false
  else ok false

/-- [cpoly::cpoly::trim]: loop body 0:
    Source: 'src/cpoly.rs', lines 55:4-60:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.trim_loop0.body
  (p : alloc.vec.Vec field.Ext4) (n : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if n > 0#usize
  then
    let i ← n - 1#usize
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i
    let b ← field.is_ezero e
    if b
    then ok (cont i)
    else ok (done n)
  else ok (done n)

/-- [cpoly::cpoly::trim]: loop 0:
    Source: 'src/cpoly.rs', lines 55:4-60:5
    Visibility: public -/
@[rust_loop]
def cpoly.trim_loop0
  (p : alloc.vec.Vec field.Ext4) (n : Std.Usize) : Result Std.Usize := do
  loop
    (fun n1 => cpoly.trim_loop0.body p n1)
    n

/-- [cpoly::cpoly::trim]: loop body 1:
    Source: 'src/cpoly.rs', lines 63:4-66:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.trim_loop1.body
  (p : alloc.vec.Vec field.Ext4) (n : Std.Usize) (r : alloc.vec.Vec field.Ext4)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < n
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i
    let r1 ← alloc.vec.Vec.push r e
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::cpoly::trim]: loop 1:
    Source: 'src/cpoly.rs', lines 63:4-66:5
    Visibility: public -/
@[rust_loop]
def cpoly.trim_loop1
  (p : alloc.vec.Vec field.Ext4) (n : Std.Usize) (r : alloc.vec.Vec field.Ext4)
  (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cpoly.trim_loop1.body p n r1 i1)
    (r, i)

/-- [cpoly::cpoly::trim]:
    Source: 'src/cpoly.rs', lines 52:0-68:1
    Visibility: public -/
def cpoly.trim
  (p : alloc.vec.Vec field.Ext4) : Result (alloc.vec.Vec field.Ext4) := do
  let n := alloc.vec.Vec.len p
  let n1 ← cpoly.trim_loop0 p n
  cpoly.trim_loop1 p n1 (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::cpoly::eval]: loop body 0:
    Source: 'src/cpoly.rs', lines 78:4-81:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.eval_loop.body
  (p : alloc.vec.Vec field.Ext4) (xv : field.Ext4) (acc : field.Ext4)
  (i : Std.Usize) :
  Result (ControlFlow (field.Ext4 × Std.Usize) field.Ext4)
  := do
  if i > 0#usize
  then
    let i1 ← i - 1#usize
    let e ← field.emul acc xv
    let e1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i1
    let acc1 ← field.eadd e e1
    ok (cont (acc1, i1))
  else ok (done acc)

/-- [cpoly::cpoly::eval]: loop 0:
    Source: 'src/cpoly.rs', lines 78:4-81:5
    Visibility: public -/
@[rust_loop]
def cpoly.eval_loop
  (p : alloc.vec.Vec field.Ext4) (xv : field.Ext4) (acc : field.Ext4)
  (i : Std.Usize) :
  Result field.Ext4
  := do
  loop
    (fun (acc1, i1) => cpoly.eval_loop.body p xv acc1 i1)
    (acc, i)

/-- [cpoly::cpoly::eval]:
    Source: 'src/cpoly.rs', lines 75:0-83:1
    Visibility: public -/
def cpoly.eval
  (p : alloc.vec.Vec field.Ext4) (xv : field.Ext4) : Result field.Ext4 := do
  let i := alloc.vec.Vec.len p
  cpoly.eval_loop p xv field.EZERO i

/-- [cpoly::cpoly::add_raw]: loop body 0:
    Source: 'src/cpoly.rs', lines 96:4-101:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.add_raw_loop.body
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4)
  (np : Std.Usize) (nq : Std.Usize) (n : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < n
  then
    let a ←
      if i < np
      then
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4)
          p i
      else ok field.EZERO
    let b ←
      if i < nq
      then
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4)
          q i
      else ok field.EZERO
    let e ← field.eadd a b
    let r1 ← alloc.vec.Vec.push r e
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::cpoly::add_raw]: loop 0:
    Source: 'src/cpoly.rs', lines 96:4-101:5
    Visibility: public -/
@[rust_loop]
def cpoly.add_raw_loop
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4)
  (np : Std.Usize) (nq : Std.Usize) (n : Std.Usize)
  (r : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cpoly.add_raw_loop.body p q np nq n r1 i1)
    (r, i)

/-- [cpoly::cpoly::add_raw]:
    Source: 'src/cpoly.rs', lines 90:0-103:1
    Visibility: public -/
def cpoly.add_raw
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let np := alloc.vec.Vec.len p
  let nq := alloc.vec.Vec.len q
  let n ← if np >= nq
            then ok np
            else ok nq
  cpoly.add_raw_loop p q np nq n (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::cpoly::add]:
    Source: 'src/cpoly.rs', lines 106:0-108:1
    Visibility: public -/
def cpoly.add
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let v ← cpoly.add_raw p q
  cpoly.trim v

/-- [cpoly::field::fneg]:
    Source: 'src/field.rs', lines 71:0-73:1
    Visibility: public -/
def field.fneg (a : Std.U64) : Result Std.U64 := do
  let i ← field.P - a
  i % field.P

/-- [cpoly::field::eneg]:
    Source: 'src/field.rs', lines 157:0-164:1
    Visibility: public -/
def field.eneg (a : field.Ext4) : Result field.Ext4 := do
  let i ← field.fneg a.c0
  let i1 ← field.fneg a.c1
  let i2 ← field.fneg a.c2
  let i3 ← field.fneg a.c3
  ok { c0 := i, c1 := i1, c2 := i2, c3 := i3 }

/-- [cpoly::cpoly::neg]: loop body 0:
    Source: 'src/cpoly.rs', lines 115:4-118:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.neg_loop.body
  (p : alloc.vec.Vec field.Ext4) (n : Std.Usize) (r : alloc.vec.Vec field.Ext4)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < n
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i
    let e1 ← field.eneg e
    let r1 ← alloc.vec.Vec.push r e1
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::cpoly::neg]: loop 0:
    Source: 'src/cpoly.rs', lines 115:4-118:5
    Visibility: public -/
@[rust_loop]
def cpoly.neg_loop
  (p : alloc.vec.Vec field.Ext4) (n : Std.Usize) (r : alloc.vec.Vec field.Ext4)
  (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cpoly.neg_loop.body p n r1 i1)
    (r, i)

/-- [cpoly::cpoly::neg]:
    Source: 'src/cpoly.rs', lines 111:0-120:1
    Visibility: public -/
def cpoly.neg
  (p : alloc.vec.Vec field.Ext4) : Result (alloc.vec.Vec field.Ext4) := do
  let n := alloc.vec.Vec.len p
  cpoly.neg_loop p n (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::cpoly::sub]:
    Source: 'src/cpoly.rs', lines 123:0-126:1
    Visibility: public -/
def cpoly.sub
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let nq ← cpoly.neg q
  cpoly.add p nq

/-- [cpoly::cpoly::smul]: loop body 0:
    Source: 'src/cpoly.rs', lines 133:4-136:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.smul_loop.body
  (r : field.Ext4) (p : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (out : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < n
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i
    let e1 ← field.emul r e
    let out1 ← alloc.vec.Vec.push out e1
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [cpoly::cpoly::smul]: loop 0:
    Source: 'src/cpoly.rs', lines 133:4-136:5
    Visibility: public -/
@[rust_loop]
def cpoly.smul_loop
  (r : field.Ext4) (p : alloc.vec.Vec field.Ext4) (n : Std.Usize)
  (out : alloc.vec.Vec field.Ext4) (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (out1, i1) => cpoly.smul_loop.body r p n out1 i1)
    (out, i)

/-- [cpoly::cpoly::smul]:
    Source: 'src/cpoly.rs', lines 129:0-138:1
    Visibility: public -/
def cpoly.smul
  (r : field.Ext4) (p : alloc.vec.Vec field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let n := alloc.vec.Vec.len p
  cpoly.smul_loop r p n (alloc.vec.Vec.new field.Ext4) 0#usize

/-- [cpoly::cpoly::mul]: loop body 0:
    Source: 'src/cpoly.rs', lines 156:4-159:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.mul_loop0.body
  (n : Std.Usize) (r : alloc.vec.Vec field.Ext4) (k : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if k < n
  then
    let r1 ← alloc.vec.Vec.push r field.EZERO
    let k1 ← k + 1#usize
    ok (cont (r1, k1))
  else ok (done r)

/-- [cpoly::cpoly::mul]: loop 0:
    Source: 'src/cpoly.rs', lines 156:4-159:5
    Visibility: public -/
@[rust_loop]
def cpoly.mul_loop0
  (r : alloc.vec.Vec field.Ext4) (n : Std.Usize) (k : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, k1) => cpoly.mul_loop0.body n r1 k1)
    (r, k)

/-- [cpoly::cpoly::mul]: loop body 2:
    Source: 'src/cpoly.rs', lines 164:8-169:9
    Visibility: public -/
@[rust_loop_body]
def cpoly.mul_loop1_loop0.body
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4)
  (nq : Std.Usize) (i : Std.Usize) (r : alloc.vec.Vec field.Ext4)
  (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if j < nq
  then
    let e ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) p
        i
    let e1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) q
        j
    let prod ← field.emul e e1
    let idx ← i + j
    let e2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice field.Ext4) r
        idx
    let e3 ← field.eadd e2 prod
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
        field.Ext4) r idx
    let j1 ← j + 1#usize
    let r1 := index_mut_back e3
    ok (cont (r1, j1))
  else ok (done r)

/-- [cpoly::cpoly::mul]: loop 2:
    Source: 'src/cpoly.rs', lines 164:8-169:9
    Visibility: public -/
@[rust_loop]
def cpoly.mul_loop1_loop0
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4)
  (nq : Std.Usize) (r : alloc.vec.Vec field.Ext4) (i : Std.Usize)
  (j : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, j1) => cpoly.mul_loop1_loop0.body p q nq i r1 j1)
    (r, j)

/-- [cpoly::cpoly::mul]: loop body 1:
    Source: 'src/cpoly.rs', lines 162:4-171:5
    Visibility: public -/
@[rust_loop_body]
def cpoly.mul_loop1.body
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4)
  (np : Std.Usize) (nq : Std.Usize) (r : alloc.vec.Vec field.Ext4)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec field.Ext4) × Std.Usize) (alloc.vec.Vec
    field.Ext4))
  := do
  if i < np
  then
    let r1 ← cpoly.mul_loop1_loop0 p q nq r i 0#usize
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::cpoly::mul]: loop 1:
    Source: 'src/cpoly.rs', lines 162:4-171:5
    Visibility: public -/
@[rust_loop]
def cpoly.mul_loop1
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4)
  (np : Std.Usize) (nq : Std.Usize) (r : alloc.vec.Vec field.Ext4)
  (i : Std.Usize) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  loop
    (fun (r1, i1) => cpoly.mul_loop1.body p q np nq r1 i1)
    (r, i)

/-- [cpoly::cpoly::mul]:
    Source: 'src/cpoly.rs', lines 146:0-173:1
    Visibility: public -/
def cpoly.mul
  (p : alloc.vec.Vec field.Ext4) (q : alloc.vec.Vec field.Ext4) :
  Result (alloc.vec.Vec field.Ext4)
  := do
  let np := alloc.vec.Vec.len p
  let nq := alloc.vec.Vec.len q
  if np = 0#usize
  then ok (alloc.vec.Vec.new field.Ext4)
  else
    if nq = 0#usize
    then ok (alloc.vec.Vec.new field.Ext4)
    else
      let i ← np + nq
      let n ← i - 1#usize
      let r ← cpoly.mul_loop0 (alloc.vec.Vec.new field.Ext4) n 0#usize
      let r1 ← cpoly.mul_loop1 p q np nq r 0#usize
      cpoly.trim r1

/-- [cpoly::field::{impl core::clone::Clone for cpoly::field::Ext4}::clone]:
    Source: 'src/field.rs', lines 86:15-86:20
    Visibility: public -/
def field.Ext4.Insts.CoreCloneClone.clone
  (self : field.Ext4) : Result field.Ext4 := do
  ok self

/-- Trait implementation: [cpoly::field::{impl core::clone::Clone for cpoly::field::Ext4}]
    Source: 'src/field.rs', lines 86:15-86:20 -/
@[reducible]
def field.Ext4.Insts.CoreCloneClone : core.clone.Clone field.Ext4 := {
  clone := field.Ext4.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [cpoly::field::{impl core::marker::Copy for cpoly::field::Ext4}]
    Source: 'src/field.rs', lines 86:9-86:13 -/
@[reducible]
def field.Ext4.Insts.CoreMarkerCopy : core.marker.Copy field.Ext4 := {
  cloneInst := field.Ext4.Insts.CoreCloneClone
}

/-- [cpoly::field::EGEN]
    Source: 'src/field.rs', lines 111:0-116:2
    Visibility: public -/
@[global_simps, irreducible]
def field.EGEN : field.Ext4 :=
  { c0 := 0#u64, c1 := 1#u64, c2 := 0#u64, c3 := 0#u64 }

/-- [cpoly::field::eof_base]:
    Source: 'src/field.rs', lines 120:0-127:1
    Visibility: public -/
def field.eof_base (a : Std.U64) : Result field.Ext4 := do
  ok { c0 := a, c1 := 0#u64, c2 := 0#u64, c3 := 0#u64 }

end cpoly
