-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [cpoly]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace cpoly

/-- [cpoly::P]
    Source: 'src/lib.rs', lines 18:0-18:30
    Visibility: public -/
@[global_simps, irreducible] def P : Std.U64 := 2013265921#u64

/-- [cpoly::fadd]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def fadd (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← a + b
  i % P

/-- [cpoly::fsub]:
    Source: 'src/lib.rs', lines 32:0-34:1
    Visibility: public -/
def fsub (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← a + P
  let i1 ← i - b
  i1 % P

/-- [cpoly::fmul]:
    Source: 'src/lib.rs', lines 37:0-39:1
    Visibility: public -/
def fmul (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  let i ← a * b
  i % P

/-- [cpoly::fneg]:
    Source: 'src/lib.rs', lines 42:0-44:1
    Visibility: public -/
def fneg (a : Std.U64) : Result Std.U64 := do
  let i ← P - a
  i % P

/-- [cpoly::c]:
    Source: 'src/lib.rs', lines 51:0-55:1
    Visibility: public -/
def c (r : Std.U64) : Result (alloc.vec.Vec Std.U64) := do
  alloc.vec.Vec.push (alloc.vec.Vec.new Std.U64) r

/-- [cpoly::x]:
    Source: 'src/lib.rs', lines 58:0-63:1
    Visibility: public -/
def x : Result (alloc.vec.Vec Std.U64) := do
  let p ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U64) 0#u64
  alloc.vec.Vec.push p 1#u64

/-- [cpoly::trim]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-79:5
    Visibility: public -/
@[rust_loop_body]
def trim_loop0.body
  (p : alloc.vec.Vec Std.U64) (n : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if n > 0#usize
  then
    let i ← n - 1#usize
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) p i
    if i1 != 0#u64
    then ok (done n)
    else ok (cont i)
  else ok (done n)

/-- [cpoly::trim]: loop 0:
    Source: 'src/lib.rs', lines 1:0-79:5
    Visibility: public -/
@[rust_loop]
def trim_loop0
  (p : alloc.vec.Vec Std.U64) (n : Std.Usize) : Result Std.Usize := do
  loop
    (fun n1 => trim_loop0.body p n1)
    n

/-- [cpoly::trim]: loop body 1:
    Source: 'src/lib.rs', lines 82:4-85:5
    Visibility: public -/
@[rust_loop_body]
def trim_loop1.body
  (p : alloc.vec.Vec Std.U64) (n : Std.Usize) (r : alloc.vec.Vec Std.U64)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.Usize) (alloc.vec.Vec
    Std.U64))
  := do
  if i < n
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) p i
    let r1 ← alloc.vec.Vec.push r i1
    let i2 ← i + 1#usize
    ok (cont (r1, i2))
  else ok (done r)

/-- [cpoly::trim]: loop 1:
    Source: 'src/lib.rs', lines 82:4-85:5
    Visibility: public -/
@[rust_loop]
def trim_loop1
  (p : alloc.vec.Vec Std.U64) (n : Std.Usize) (r : alloc.vec.Vec Std.U64)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (r1, i1) => trim_loop1.body p n r1 i1)
    (r, i)

/-- [cpoly::trim]:
    Source: 'src/lib.rs', lines 71:0-87:1
    Visibility: public -/
def trim (p : alloc.vec.Vec Std.U64) : Result (alloc.vec.Vec Std.U64) := do
  let n := alloc.vec.Vec.len p
  let n1 ← trim_loop0 p n
  trim_loop1 p n1 (alloc.vec.Vec.new Std.U64) 0#usize

/-- [cpoly::eval]: loop body 0:
    Source: 'src/lib.rs', lines 97:4-100:5
    Visibility: public -/
@[rust_loop_body]
def eval_loop.body
  (p : alloc.vec.Vec Std.U64) (xv : Std.U64) (acc : Std.U64) (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.Usize) Std.U64)
  := do
  if i > 0#usize
  then
    let i1 ← i - 1#usize
    let i2 ← fmul acc xv
    let i3 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) p i1
    let acc1 ← fadd i2 i3
    ok (cont (acc1, i1))
  else ok (done acc)

/-- [cpoly::eval]: loop 0:
    Source: 'src/lib.rs', lines 97:4-100:5
    Visibility: public -/
@[rust_loop]
def eval_loop
  (p : alloc.vec.Vec Std.U64) (xv : Std.U64) (acc : Std.U64) (i : Std.Usize) :
  Result Std.U64
  := do
  loop
    (fun (acc1, i1) => eval_loop.body p xv acc1 i1)
    (acc, i)

/-- [cpoly::eval]:
    Source: 'src/lib.rs', lines 94:0-102:1
    Visibility: public -/
def eval (p : alloc.vec.Vec Std.U64) (xv : Std.U64) : Result Std.U64 := do
  let i := alloc.vec.Vec.len p
  eval_loop p xv 0#u64 i

/-- [cpoly::add_raw]: loop body 0:
    Source: 'src/lib.rs', lines 115:4-120:5
    Visibility: public -/
@[rust_loop_body]
def add_raw_loop.body
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) (np : Std.Usize)
  (nq : Std.Usize) (n : Std.Usize) (r : alloc.vec.Vec Std.U64) (i : Std.Usize)
  :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.Usize) (alloc.vec.Vec
    Std.U64))
  := do
  if i < n
  then
    let a ←
      if i < np
      then
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) p i
      else ok 0#u64
    let b ←
      if i < nq
      then
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) q i
      else ok 0#u64
    let i1 ← fadd a b
    let r1 ← alloc.vec.Vec.push r i1
    let i2 ← i + 1#usize
    ok (cont (r1, i2))
  else ok (done r)

/-- [cpoly::add_raw]: loop 0:
    Source: 'src/lib.rs', lines 115:4-120:5
    Visibility: public -/
@[rust_loop]
def add_raw_loop
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) (np : Std.Usize)
  (nq : Std.Usize) (n : Std.Usize) (r : alloc.vec.Vec Std.U64) (i : Std.Usize)
  :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (r1, i1) => add_raw_loop.body p q np nq n r1 i1)
    (r, i)

/-- [cpoly::add_raw]:
    Source: 'src/lib.rs', lines 109:0-122:1
    Visibility: public -/
def add_raw
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let np := alloc.vec.Vec.len p
  let nq := alloc.vec.Vec.len q
  let n ← if np >= nq
            then ok np
            else ok nq
  add_raw_loop p q np nq n (alloc.vec.Vec.new Std.U64) 0#usize

/-- [cpoly::add]:
    Source: 'src/lib.rs', lines 125:0-127:1
    Visibility: public -/
def add
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let v ← add_raw p q
  trim v

/-- [cpoly::neg]: loop body 0:
    Source: 'src/lib.rs', lines 134:4-137:5
    Visibility: public -/
@[rust_loop_body]
def neg_loop.body
  (p : alloc.vec.Vec Std.U64) (n : Std.Usize) (r : alloc.vec.Vec Std.U64)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.Usize) (alloc.vec.Vec
    Std.U64))
  := do
  if i < n
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) p i
    let i2 ← fneg i1
    let r1 ← alloc.vec.Vec.push r i2
    let i3 ← i + 1#usize
    ok (cont (r1, i3))
  else ok (done r)

/-- [cpoly::neg]: loop 0:
    Source: 'src/lib.rs', lines 134:4-137:5
    Visibility: public -/
@[rust_loop]
def neg_loop
  (p : alloc.vec.Vec Std.U64) (n : Std.Usize) (r : alloc.vec.Vec Std.U64)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (r1, i1) => neg_loop.body p n r1 i1)
    (r, i)

/-- [cpoly::neg]:
    Source: 'src/lib.rs', lines 130:0-139:1
    Visibility: public -/
def neg (p : alloc.vec.Vec Std.U64) : Result (alloc.vec.Vec Std.U64) := do
  let n := alloc.vec.Vec.len p
  neg_loop p n (alloc.vec.Vec.new Std.U64) 0#usize

/-- [cpoly::sub]:
    Source: 'src/lib.rs', lines 142:0-145:1
    Visibility: public -/
def sub
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let nq ← neg q
  add p nq

/-- [cpoly::smul]: loop body 0:
    Source: 'src/lib.rs', lines 152:4-155:5
    Visibility: public -/
@[rust_loop_body]
def smul_loop.body
  (r : Std.U64) (p : alloc.vec.Vec Std.U64) (n : Std.Usize)
  (out : alloc.vec.Vec Std.U64) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.Usize) (alloc.vec.Vec
    Std.U64))
  := do
  if i < n
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) p i
    let i2 ← fmul r i1
    let out1 ← alloc.vec.Vec.push out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [cpoly::smul]: loop 0:
    Source: 'src/lib.rs', lines 152:4-155:5
    Visibility: public -/
@[rust_loop]
def smul_loop
  (r : Std.U64) (p : alloc.vec.Vec Std.U64) (n : Std.Usize)
  (out : alloc.vec.Vec Std.U64) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (out1, i1) => smul_loop.body r p n out1 i1)
    (out, i)

/-- [cpoly::smul]:
    Source: 'src/lib.rs', lines 148:0-157:1
    Visibility: public -/
def smul
  (r : Std.U64) (p : alloc.vec.Vec Std.U64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let n := alloc.vec.Vec.len p
  smul_loop r p n (alloc.vec.Vec.new Std.U64) 0#usize

/-- [cpoly::mul]: loop body 0:
    Source: 'src/lib.rs', lines 170:4-173:5
    Visibility: public -/
@[rust_loop_body]
def mul_loop0.body
  (n : Std.Usize) (r : alloc.vec.Vec Std.U64) (k : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.Usize) (alloc.vec.Vec
    Std.U64))
  := do
  if k < n
  then
    let r1 ← alloc.vec.Vec.push r 0#u64
    let k1 ← k + 1#usize
    ok (cont (r1, k1))
  else ok (done r)

/-- [cpoly::mul]: loop 0:
    Source: 'src/lib.rs', lines 170:4-173:5
    Visibility: public -/
@[rust_loop]
def mul_loop0
  (r : alloc.vec.Vec Std.U64) (n : Std.Usize) (k : Std.Usize) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (r1, k1) => mul_loop0.body n r1 k1)
    (r, k)

/-- [cpoly::mul]: loop body 2:
    Source: 'src/lib.rs', lines 178:8-183:9
    Visibility: public -/
@[rust_loop_body]
def mul_loop1_loop0.body
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) (nq : Std.Usize)
  (i : Std.Usize) (r : alloc.vec.Vec Std.U64) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.Usize) (alloc.vec.Vec
    Std.U64))
  := do
  if j < nq
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) p i
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) q j
    let prod ← fmul i1 i2
    let idx ← i + j
    let i3 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64) r idx
    let i4 ← fadd i3 prod
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U64) r
        idx
    let j1 ← j + 1#usize
    let r1 := index_mut_back i4
    ok (cont (r1, j1))
  else ok (done r)

/-- [cpoly::mul]: loop 2:
    Source: 'src/lib.rs', lines 178:8-183:9
    Visibility: public -/
@[rust_loop]
def mul_loop1_loop0
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) (nq : Std.Usize)
  (r : alloc.vec.Vec Std.U64) (i : Std.Usize) (j : Std.Usize) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (r1, j1) => mul_loop1_loop0.body p q nq i r1 j1)
    (r, j)

/-- [cpoly::mul]: loop body 1:
    Source: 'src/lib.rs', lines 176:4-185:5
    Visibility: public -/
@[rust_loop_body]
def mul_loop1.body
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) (np : Std.Usize)
  (nq : Std.Usize) (r : alloc.vec.Vec Std.U64) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U64) × Std.Usize) (alloc.vec.Vec
    Std.U64))
  := do
  if i < np
  then
    let r1 ← mul_loop1_loop0 p q nq r i 0#usize
    let i1 ← i + 1#usize
    ok (cont (r1, i1))
  else ok (done r)

/-- [cpoly::mul]: loop 1:
    Source: 'src/lib.rs', lines 176:4-185:5
    Visibility: public -/
@[rust_loop]
def mul_loop1
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) (np : Std.Usize)
  (nq : Std.Usize) (r : alloc.vec.Vec Std.U64) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U64)
  := do
  loop
    (fun (r1, i1) => mul_loop1.body p q np nq r1 i1)
    (r, i)

/-- [cpoly::mul]:
    Source: 'src/lib.rs', lines 160:0-187:1
    Visibility: public -/
def mul
  (p : alloc.vec.Vec Std.U64) (q : alloc.vec.Vec Std.U64) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let np := alloc.vec.Vec.len p
  let nq := alloc.vec.Vec.len q
  if np = 0#usize
  then ok (alloc.vec.Vec.new Std.U64)
  else
    if nq = 0#usize
    then ok (alloc.vec.Vec.new Std.U64)
    else
      let i ← np + nq
      let n ← i - 1#usize
      let r ← mul_loop0 (alloc.vec.Vec.new Std.U64) n 0#usize
      let r1 ← mul_loop1 p q np nq r 0#usize
      trim r1

end cpoly
